
// This file has been generated by the GUI designer. Do not modify.
namespace Quiz
{
	public partial class ScoreObject
	{
		public virtual void Build ()
		{
			// Action group Quiz.ScoreObject
		}
	}
}
