
// This file has been generated by the GUI designer. Do not modify.
namespace Quiz
{
	public partial class QuizWindow
	{
		private global::Gtk.Table table1;
		
		private global::Quiz.QuizWidget quizwidget1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Quiz.QuizWindow
			this.Name = "Quiz.QuizWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("QuizWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Container child Quiz.QuizWindow.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(1)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.quizwidget1 = new global::Quiz.QuizWidget ();
			this.quizwidget1.Events = ((global::Gdk.EventMask)(256));
			this.quizwidget1.Name = "quizwidget1";
			this.table1.Add (this.quizwidget1);
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 513;
			this.DefaultHeight = 362;
			this.Show ();
		}
	}
}
